# Generated by Django 4.1.7 on 2023-03-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autocapacitaciones',
            fields=[
                ('idautocap', models.AutoField(db_column='idAutoCap', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('link', models.TextField()),
                ('fechainicial', models.DateField(db_column='fechaInicial')),
                ('fechafinal', models.DateField(db_column='fechaFinal')),
                ('cvelocal', models.IntegerField(db_column='cveLocal')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(db_column='idContrato', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoMes',
            fields=[
                ('idempleado_mes', models.AutoField(db_column='idEmpleado_mes', primary_key=True, serialize=False)),
                ('cveusuario', models.IntegerField(db_column='cveUsuario')),
                ('fecha', models.IntegerField()),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafinal', models.DateField(db_column='fechaFinal')),
                ('posicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imgvideo',
            fields=[
                ('idimgvideo', models.AutoField(db_column='idImgVideo', primary_key=True, serialize=False)),
                ('fechainicial', models.DateField(db_column='fechaInicial')),
                ('fechafinal', models.DateField(db_column='fechaFinal')),
                ('imgvideo', models.CharField(db_column='imgVideo', max_length=150)),
                ('formato', models.CharField(max_length=15)),
                ('cvelocal', models.IntegerField(db_column='cveLocal')),
                ('cveseccion', models.IntegerField(db_column='cveSeccion')),
                ('link', models.TextField(blank=True, null=True)),
                ('posicion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idlocal', models.AutoField(db_column='idLocal', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idmenu', models.AutoField(db_column='idMenu', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('cvelocal', models.IntegerField(db_column='cveLocal')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idnoticia', models.AutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('fechainicial', models.DateField(db_column='fechaInicial')),
                ('fechafinal', models.DateField(db_column='fechaFinal')),
                ('imgvideo', models.CharField(db_column='imgVideo', max_length=150)),
                ('formato', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=450)),
                ('cvelocal', models.IntegerField(db_column='cveLocal')),
                ('link', models.TextField()),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('idseccion', models.AutoField(db_column='idSeccion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('nombres', models.CharField(max_length=30)),
                ('apellidopaterno', models.CharField(db_column='apellidoPaterno', max_length=25)),
                ('apellidomaterno', models.CharField(db_column='apellidoMaterno', max_length=25)),
                ('correo', models.CharField(max_length=55)),
                ('contrasena', models.TextField()),
                ('cverol', models.IntegerField(db_column='cveRol')),
                ('img', models.CharField(max_length=20)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
                ('departamento', models.CharField(max_length=35)),
                ('contrato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('idvisita', models.AutoField(db_column='idVisita', primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('contador', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
